name: API TESTS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [10]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node v${{ matrix.node }} setup
        uses: actions/setup-node@v2.1.4
      - name: install dependencies
        run: npm run unix:pre-test
      - name: standard lint
        run: npm run lint:fix

  integrations:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [10]

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node v${{ matrix.node }} setup
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}
      - name: install dependencies
        run: npm run unix:pre-test
      - name: integration tests
        run: npm run cy:run
        env:
          APP_URL: "https://gorest.co.in/public-api"
          CI: true
